name: watut
version: '1.0.0'
main: me.slide.watut.WatutPlugin
author: Slide_AM
description: Bukkit bridge for What Are They Up To (Watut)
website: https://github.com/AdamMekush/WATUT-PLUGIN
api-version: '1.20'
folia-supported: true